name: 'Generate Plantuml'
description: 'Generate uml diagrams with Plantuml Server and push them to your repository.'
author: 'grassedge'
inputs:
  path:
    description: 'path to directory which generated svg is stored'
    default: '.'
  message:
    description: 'the commit message when committing generated images'
    default: 'Render PlantUML files'
  server:
    description: 'Base URL to PlantUML server'
    default: 'https://www.plantuml.com/plantuml/'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'image'
  color: 'gray-dark'
